services:
  - type: web
    name: porima-stock-monitor
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker --bind 0.0.0.0:$PORT porima_web:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
